### ISSUE TITLE
Оптимизировать PixelDrawer используя одномерный массив

### ISSUE THREAD

**Issue by FrediKats** [kysect/Efilir#6]
Во время отрисовки геенрится byte[,,], который потом конвертится в byte[]. Это х2 аллокации и лишние затраты на отрисовку, которые растут при увеличении поля очень сильно. Можно оптимизировать и сразу на одномерном делать.

**Comment by Mihinator3000** [comment]
@FrediKats, надеюсь проект еще живой, я вроде пофиксил ишью, глянешь пр?

**Comment by FrediKats** [comment]
Closed #7
